# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='categoria')),
            ],
            options={
                'ordering': ['category'],
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor', models.CharField(max_length=50, unique=True, verbose_name='distribudor')),
            ],
            options={
                'ordering': ['distributor'],
                'verbose_name': 'distribuidor',
                'verbose_name_plural': 'distribuidores',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100, verbose_name='filme')),
                ('raised', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='arrecadou')),
                ('liked', models.BooleanField(default=True, verbose_name='gostou')),
                ('release', models.DateTimeField(verbose_name='lançamento')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_category', to='core.Category', verbose_name='categoria')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_distributor', to='core.Distributor', verbose_name='distributor')),
            ],
            options={
                'ordering': ['-release'],
                'verbose_name': 'filme',
                'verbose_name_plural': 'filmes',
            },
        ),
    ]
